### ISSUE TITLE
Si installa ma non funziona

### ISSUE THREAD

**Issue by Testato** [NeverWise/plugin.video.fattoquotidianotv#2]
Ciao,
non viene visualizzato nessun video, testao su Linux, Android, Windows
Kodi 17.6

**Comment by Testato** [comment]
sembra ci sia un problema di importazione di Util ?
```
from neverwise import Util
ImportError: cannot import name Util
```

**Comment by NeverWise** [comment]
Purtroppo questo plugin (insieme ad altri) non viene più mantenuto perché i contenuti non mi sembrano adeguati allo scopo per cui kodi è sviluppato.
